<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/mUbOTaQTiWsAAAAAGSAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M15.827 5.5H19.43L26 21.98H22.397L15.827 5.5ZM8.569 5.5H12.336L18.906 21.98H15.232L13.889 18.519H7.017L5.673 21.979H2L8.57 5.502L8.569 5.5ZM12.701 15.459L10.453 9.667L8.205 15.46H12.7L12.701 15.459Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Anthropic', inheritAttrs: false };
</script>
