<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/oG5VTKJL19UAAAAAIPAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="62" height="8" viewBox="0 0 62 8" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M61 4H6" stroke="currentColor" style="stroke-opacity:1;" stroke-width="2" stroke-linecap="round"/> <path d="M1 4L6 7L6 1L1 4Z" fill="currentColor" stroke="currentColor" style="fill-opacity:1;stroke-opacity:1;" stroke-width="2" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'ArrowLeftLong', inheritAttrs: false };
</script>
