<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/ijf9S7gDjcoAAAAAEzAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M4 10.5L8 6.5L12 10.5" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'ArrowUp', inheritAttrs: false };
</script>
