<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/XF5RRJ2aZ4EAAAAAIPAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="8" height="62" viewBox="0 0 8 62" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M4 61L4 6" stroke="currentColor" style="stroke-opacity:1;" stroke-width="2" stroke-linecap="round"/> <path d="M4 1L7 6H1L4 1Z" fill="currentColor" stroke="currentColor" style="fill-opacity:1;stroke-opacity:1;" stroke-width="2" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'ArrowTopLong', inheritAttrs: false };
</script>
