<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/RdTaQpJhFh8AAAAAIFAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="14" height="15" viewBox="0 0 14 15" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M5.25 7.49984H8.75M5.25 5.1665H7M5.25 9.83317H8.75M10.5 1.6665H3.5C2.5335 1.6665 1.75 2.45001 1.75 3.4165V11.5832C1.75 12.5497 2.5335 13.3332 3.5 13.3332H10.5C11.4665 13.3332 12.25 12.5497 12.25 11.5832V3.4165C12.25 2.45001 11.4665 1.6665 10.5 1.6665Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.16667" stroke-linecap="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'BasicInfo', inheritAttrs: false };
</script>
