<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/tUWcQqo6mkkAAAAAJ6AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M10 0C15.5228 0 20 4.47715 20 10C20 15.5228 15.5228 20 10 20C4.47715 20 0 15.5228 0 10C0 4.47715 4.47715 0 10 0ZM14.7559 6.70215C14.4305 6.37697 13.9025 6.37702 13.5771 6.70215L8.33301 11.9463L6.42188 10.0352C6.09655 9.7102 5.5695 9.71024 5.24414 10.0352C4.91876 10.3605 4.91888 10.8884 5.24414 11.2139L7.74414 13.7139C8.0695 14.0389 8.59652 14.0389 8.92188 13.7139L14.7559 7.87988C15.0806 7.55451 15.0808 7.02742 14.7559 6.70215Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Checked', inheritAttrs: false };
</script>
