<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/V1ruT5OjiBAAAAAAExAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M10 12L6 8L10 4" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'Chevron_left', inheritAttrs: false };
</script>
