<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Bz1DSblMgOMAAAAALPAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M11.6547 12.5955L7.99968 8.94051L4.34538 12.5948C4.08568 12.8545 3.66457 12.8545 3.40487 12.5948C3.1454 12.3351 3.14525 11.9139 3.40487 11.6543L7.05918 8L3.40487 4.34569C3.14525 4.08607 3.1454 3.6649 3.40487 3.40519C3.66457 3.14549 4.08568 3.14549 4.34538 3.40519L7.99968 7.05949L11.6547 3.4045C11.9143 3.1451 12.3355 3.1451 12.5952 3.4045C12.8548 3.66412 12.8547 4.08529 12.5952 4.345L8.94019 8L12.5952 11.655C12.8547 11.9147 12.8548 12.3359 12.5952 12.5955C12.3355 12.8549 11.9143 12.8549 11.6547 12.5955Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Close', inheritAttrs: false };
</script>
