<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/n0XWRZbBRisAAAAAK2AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="14" height="15" viewBox="0 0 14 15" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M3.79102 4.00016V3.7085C3.79102 2.742 4.57452 1.9585 5.54102 1.9585H10.791C11.7575 1.9585 12.541 2.742 12.541 3.7085V8.9585C12.541 9.92499 11.7575 10.7085 10.791 10.7085H10.4993M8.16602 4.5835H2.91602C1.94952 4.5835 1.16602 5.367 1.16602 6.3335V11.5835C1.16602 12.55 1.94952 13.3335 2.91602 13.3335H8.16602C9.13251 13.3335 9.91602 12.55 9.91602 11.5835V6.3335C9.91602 5.367 9.13251 4.5835 8.16602 4.5835Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'Copy', inheritAttrs: false };
</script>
