<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Yef7T7-ndKMAAAAAOJAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M4.15 7.23108H5.05M14.95 12.6311H15.85M1 14.1589V5.19694C1 4.54114 1.44633 3.9695 2.08255 3.81044L2.67 3.66358C5.09914 3.05629 7.65552 3.2019 10 4.08108C12.3445 4.96026 14.9009 5.10586 17.33 4.49858L17.4262 4.47452C18.2256 4.27467 19 4.87928 19 5.70327V14.6652C19 15.321 18.5537 15.8927 17.9175 16.0517L17.33 16.1986C14.9009 16.8059 12.3445 16.6603 10 15.7811C7.65552 14.9019 5.09914 14.7563 2.66999 15.3636L2.57376 15.3876C1.77437 15.5875 1 14.9829 1 14.1589ZM12.25 9.93108C12.25 11.1737 11.2426 12.1811 10 12.1811C8.75736 12.1811 7.75 11.1737 7.75 9.93108C7.75 8.68844 8.75736 7.68108 10 7.68108C11.2426 7.68108 12.25 8.68844 12.25 9.93108Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.66" stroke-linecap="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'Costs', inheritAttrs: false };
</script>
