<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/BHInTK3HO20AAAAAKVAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M22.7588 5.63184C22.8529 5.89033 22.9205 6.16127 22.96 6.44141C22.9855 6.624 23 6.81037 23 7V17C23 19.2091 21.2091 21 19 21H5C2.79086 21 1 19.2091 1 17V7C1 6.51943 1.08487 6.05869 1.24023 5.63184L9.54395 12.0898C10.9884 13.2133 13.0116 13.2133 14.4561 12.0898L22.7588 5.63184Z" fill="currentColor" style="fill-opacity:1;"/> <path d="M19 3C19.975 3 20.8684 3.34901 21.5625 3.92871L13.2412 10.5176C12.5139 11.0931 11.4861 11.0931 10.7588 10.5176L2.43652 3.92871C3.13066 3.34872 4.02471 3 5 3H19Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Email', inheritAttrs: false };
</script>
