<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/fd_CRIIqAQcAAAAAHwAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="14" height="15" viewBox="0 0 14 15" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M6.38597 3.41667H3.5C2.5335 3.41667 1.75 4.20017 1.75 5.16667V11C1.75 11.9665 2.5335 12.75 3.5 12.75H9.33333C10.2998 12.75 11.0833 11.9665 11.0833 11V8.12939M11.375 3.125L6.70833 7.79167M9.33333 2.25H11.9583C12.1194 2.25 12.25 2.38058 12.25 2.54167V5.16667" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'ExternalOpen', inheritAttrs: false };
</script>
