<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/awJESJOCOb8AAAAAJhAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="17" height="16" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M10.3307 2.66667V4C10.3307 4.73638 10.9277 5.33333 11.6641 5.33333H14.3307M5.66406 7.33333H8.9974M5.66406 10H10.9974M14.9974 6.36257V12C14.9974 13.1046 14.102 14 12.9974 14H3.66406C2.55949 14 1.66406 13.1046 1.66406 12V4C1.66406 2.89543 2.55949 2 3.66406 2H9.6898C10.1066 2 10.5131 2.13025 10.8523 2.37253L14.1599 4.7351C14.6855 5.11053 14.9974 5.71667 14.9974 6.36257Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'File', inheritAttrs: false };
</script>
