<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/rSQSTqVjyUAAAAAAHYAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <circle cx="5.33301" cy="8" r="2" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333"/> <rect x="0.666992" y="3.33331" width="14.6667" height="9.33333" rx="4.66667" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconSwitch', inheritAttrs: false };
</script>
