<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/VEaoSIAm4KsAAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_5155_73821)"> <path d="M7.59267 1H4.41645C3.83469 1 3.28177 1.25331 2.90185 1.69387L1.14959 3.72581C0.514479 4.46229 0.5012 5.54888 1.11813 6.30066L4.4607 10.3739C5.25868 11.3463 6.74556 11.3494 7.54756 10.3803L10.9151 6.31123C11.5406 5.5554 11.5255 4.45744 10.8794 3.7191L9.09783 1.68299C8.71805 1.24896 8.1694 1 7.59267 1Z" stroke="currentColor" style="stroke-opacity:1;" stroke-linecap="round" stroke-linejoin="round"/> <path d="M7.25 4L7.20569 3.91138C7.07514 3.65027 6.83701 3.45925 6.5538 3.38845L6.51313 3.37828C6.18201 3.2955 5.8322 3.3339 5.52692 3.48654C5.20399 3.64801 5 3.97807 5 4.33911V4.38197C5 4.76074 5.214 5.107 5.55279 5.27639L6.44721 5.72361C6.786 5.893 7 6.23926 7 6.61803V6.66089C7 7.02193 6.79601 7.35199 6.47308 7.51346C6.1678 7.6661 5.81799 7.7045 5.48687 7.62172L5.4462 7.61155C5.16299 7.54075 4.92486 7.34973 4.79431 7.08862L4.75 7" stroke="currentColor" style="stroke-opacity:1;" stroke-linecap="round" stroke-linejoin="round"/> </g> <defs> <clipPath id="clip0_5155_73821"> <rect width="12" height="12" fill="currentColor" style="fill-opacity:1;"/> </clipPath> </defs> </svg>
</template>

<script lang="ts">
export default { name: 'IconSubscriptionWallet', inheritAttrs: false };
</script>
