<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Shs7QqrywxkAAAAAQCAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M4.66602 5.3335V10.6668" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M8 2.6665V13.3332" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M11.334 8V10.6667" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M14.666 7.3335V8.00016" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M1.33398 7.3335V8.00016" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M12.4166 1.34237C12.5025 1.11021 12.8309 1.11021 12.9168 1.34237L13.3444 2.49793C13.3714 2.57092 13.4289 2.62847 13.5019 2.65548L14.6575 3.08308C14.8896 3.16899 14.8896 3.49736 14.6575 3.58326L13.5019 4.01086C13.4289 4.03787 13.3714 4.09542 13.3444 4.16841L12.9168 5.32397C12.8309 5.55613 12.5025 5.55613 12.4166 5.32397L11.989 4.16841C11.962 4.09542 11.9044 4.03787 11.8314 4.01086L10.6759 3.58326C10.4437 3.49736 10.4437 3.16899 10.6759 3.08308L11.8314 2.65548C11.9044 2.62847 11.962 2.57092 11.989 2.49793L12.4166 1.34237Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="0.933333" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconVoice', inheritAttrs: false };
</script>
