<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/ENG5R7vVhCAAAAAAM1AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M13.3333 7.33301V4C13.3333 3.26362 12.7357 2.66602 11.9993 2.66602H8.66634C8.29815 2.66602 7.99935 2.96482 7.99935 3.33301C7.99935 3.7012 8.29815 4 8.66634 4H11.9993V7.33301C11.9993 7.7012 12.2982 8 12.6663 8C13.0345 8 13.3333 7.7012 13.3333 7.33301Z" fill="currentColor" style="fill-opacity:1;"/> <path d="M2.66602 8.66634V11.9993C2.66602 12.7357 3.26362 13.3333 4 13.3333H7.33301C7.7012 13.3333 8 13.0345 8 12.6663C8 12.2982 7.7012 11.9993 7.33301 11.9993H4V8.66634C4 8.29815 3.7012 7.99935 3.33301 7.99935C2.96482 7.99935 2.66602 8.29815 2.66602 8.66634Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconExpand', inheritAttrs: false };
</script>
