<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/n9VgQ6ReImIAAAAAMYAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M3.33337 8.66694C3.33337 6.8261 4.82558 5.33313 6.66638 5.33296H11.724L10.1957 6.86225C9.93533 7.1226 9.93533 7.54429 10.1957 7.80464C10.456 8.06482 10.8778 8.06493 11.1381 7.80464L13.8051 5.13765C14.065 4.87732 14.0651 4.45552 13.8051 4.19526L11.1381 1.52827C10.8778 1.26819 10.456 1.2683 10.1957 1.52827C9.93533 1.78862 9.93533 2.21128 10.1957 2.47163L11.724 3.99995H6.66638C4.0892 4.00013 2.00037 6.08972 2.00037 8.66694C2.00054 11.244 4.08931 13.3328 6.66638 13.333H13.3334C13.7015 13.333 14.0002 13.035 14.0004 12.6669C14.0004 12.2988 13.7016 11.9999 13.3334 11.9999H6.66638C4.82569 11.9998 3.33355 10.5076 3.33337 8.66694Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconRedo', inheritAttrs: false };
</script>
