<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/y6buSouTSLoAAAAALGAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M12.3124 11.75C12.8301 11.75 13.2499 11.3303 13.2499 10.8125L13.2499 5.1875C13.2499 4.66973 12.8301 4.25 12.3124 4.25L3.68738 4.25C3.16961 4.25 2.74988 4.66973 2.74988 5.1875L2.74988 10.8125C2.74988 11.3303 3.16961 11.75 3.68738 11.75L12.3124 11.75ZM3.68738 13.25C2.34118 13.25 1.24988 12.1587 1.24988 10.8125L1.24988 5.1875C1.24988 3.84131 2.34118 2.75 3.68738 2.75L12.3124 2.75C13.6586 2.75 14.7499 3.84131 14.7499 5.1875L14.7499 10.8125C14.7499 12.1587 13.6586 13.25 12.3124 13.25L3.68738 13.25Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Icon4_3', inheritAttrs: false };
</script>
