<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/QnG0Taq26bkAAAAAMMAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M4 6.66675C4.7363 6.66675 5.33288 7.26349 5.33301 7.99976C5.33301 8.73614 4.73638 9.33374 4 9.33374C3.26362 9.33374 2.66699 8.73614 2.66699 7.99976C2.66712 7.26349 3.2637 6.66675 4 6.66675ZM8 6.66675C8.7363 6.66675 9.33288 7.26349 9.33301 7.99976C9.33301 8.73614 8.73638 9.33374 8 9.33374C7.26362 9.33374 6.66699 8.73614 6.66699 7.99976C6.66712 7.26349 7.2637 6.66675 8 6.66675ZM12 6.66675C12.7363 6.66675 13.3329 7.26349 13.333 7.99976C13.333 8.73614 12.7364 9.33374 12 9.33374C11.2636 9.33374 10.667 8.73614 10.667 7.99976C10.6671 7.26349 11.2637 6.66675 12 6.66675Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconMore_large_h', inheritAttrs: false };
</script>
