<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/1H-hSrW6UmQAAAAAKmAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M13.3331 6.47607C13.333 6.2133 13.1203 6.00064 12.8575 6.00049H3.1427C2.87993 6.00064 2.66727 6.2133 2.66711 6.47607V9.3335C2.66711 9.5964 2.87984 9.80991 3.1427 9.81006H12.8575C13.1204 9.80991 13.3331 9.5964 13.3331 9.3335V6.47607ZM14.6671 9.3335C14.6671 10.3328 13.8568 11.1429 12.8575 11.1431H3.1427C2.14346 11.1429 1.33313 10.3328 1.33313 9.3335V6.47607C1.33328 5.47692 2.14355 4.66665 3.1427 4.6665H12.8575C13.8567 4.66665 14.667 5.47692 14.6671 6.47607V9.3335Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Icon21_9', inheritAttrs: false };
</script>
