<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/EXImRrTz-CIAAAAAMMAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <rect x="4.66602" y="0.666626" width="6.66667" height="10" rx="3.33333" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333"/> <path d="M8 13.3334V15.3334" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M2 7.33337C2 10.6471 4.68629 13.3334 8 13.3334C11.3137 13.3334 14 10.6471 14 7.33337" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconMic', inheritAttrs: false };
</script>
