<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/z8niTrp7VCsAAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" v-bind="$attrs">
<path d="M4 12.65V4.927l-.861.862a.667.667 0 0 1-.944-.944l2-2 .102-.083a.67.67 0 0 1 .842.083l2 2a.667.667 0 0 1-.944.944l-.861-.862v7.723a.667.667 0 0 1-1.334 0m6.667-9.333a.667.667 0 0 1 1.333 0v7.725l.862-.863a.666.666 0 1 1 .943.943l-2 2a.666.666 0 0 1-.943 0l-2-2a.666.666 0 0 1 .943-.943l.862.863z" fill="currentColor"/>
</svg>
</template>

<script lang="ts">
export default { name: 'IconRerank', inheritAttrs: false };
</script>
