<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/JU5cT6lrUAgAAAAAJZAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M16.6663 2.5L11.2497 7.91667M8.33301 10.8333L2.08301 17.5M2.55594 2.5H5.85936C6.10668 2.5 6.34122 2.60985 6.49955 2.79985L18.1802 16.8166C18.4063 17.088 18.2133 17.5 17.8601 17.5H14.5567C14.3093 17.5 14.0748 17.3901 13.9165 17.2002L2.23585 3.18341C2.00969 2.91202 2.20268 2.5 2.55594 2.5Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.66667" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconX', inheritAttrs: false };
</script>
