<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/97a9Ta-cnmMAAAAAHsAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M5.33333 6.33333V5.33333H10.6667V6.33333M8 5.33333V10.6667M6.66667 10.6667H9.33333M12 2H4C2.89543 2 2 2.89543 2 4V12C2 13.1046 2.89543 14 4 14H12C13.1046 14 14 13.1046 14 12V4C14 2.89543 13.1046 2 12 2Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconText_rectangle', inheritAttrs: false };
</script>
