<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/wCC9Q6WuBQ4AAAAAGCAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M11.0835 6.41663L7.00016 2.33329M7.00016 2.33329L2.91683 6.41663M7.00016 2.33329L7.00016 11.6666" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconArrow_up', inheritAttrs: false };
</script>
