<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/PIypTL6PlG4AAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <circle cx="10" cy="11.3333" r="2" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333"/> <path d="M0.666992 4.66675H3.33366" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M12.667 11.3333H15.3337" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M8.66699 4.66675L15.3337 4.66675" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M0.666992 11.3333L7.33366 11.3333" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <circle cx="6" cy="4.66675" r="2" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconSetting_03', inheritAttrs: false };
</script>
