<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Qcp-RqHMHC8AAAAALYAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M11.333 7C11.333 4.60677 9.39323 2.66699 7 2.66699C4.60677 2.66699 2.66699 4.60677 2.66699 7C2.66699 9.39323 4.60677 11.333 7 11.333C9.39323 11.333 11.333 9.39323 11.333 7ZM12.667 7C12.667 8.32461 12.2108 9.54196 11.4492 10.5068L14.4717 13.5283C14.732 13.7887 14.732 14.2113 14.4717 14.4717C14.2113 14.732 13.7887 14.732 13.5283 14.4717L10.5068 11.4492C9.54196 12.2108 8.32461 12.667 7 12.667C3.87039 12.667 1.33301 10.1296 1.33301 7C1.33301 3.87039 3.87039 1.33301 7 1.33301C10.1296 1.33301 12.667 3.87039 12.667 7Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconSearch', inheritAttrs: false };
</script>
