<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/2XOwRo-WYioAAAAAIZAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M12 0C18.6274 0 24 5.37258 24 12C24 18.6274 18.6274 24 12 24C5.37258 24 0 18.6274 0 12C0 5.37258 5.37258 0 12 0ZM9.59961 8C8.71626 8.00021 8.00021 8.71626 8 9.59961V14.4004C8.00021 15.2837 8.71626 15.9998 9.59961 16H14.4004C15.2837 15.9998 15.9998 15.2837 16 14.4004V9.59961C15.9998 8.71626 15.2837 8.00021 14.4004 8H9.59961Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconStop', inheritAttrs: false };
</script>
