<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/P0R6RqL-bfkAAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <circle cx="10" cy="11.3335" r="2" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333"/> <path d="M0.666016 4.6665H3.33268" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M12.666 11.3335H15.3327" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M8.66602 4.6665L15.3327 4.6665" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M0.666016 11.3335L7.33268 11.3335" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <circle cx="6" cy="4.6665" r="2" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconSetting', inheritAttrs: false };
</script>
