<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Fx2sTZWJ74MAAAAAKUAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M13.1382 8.19507C13.3986 8.45542 13.3986 8.87808 13.1382 9.13843L8.47124 13.8044C8.21089 14.0648 7.78921 14.0648 7.52886 13.8044L2.86187 9.13843C2.60152 8.87808 2.60152 8.45542 2.86187 8.19507C3.12212 7.93499 3.54393 7.9351 3.80425 8.19507L7.33355 11.7244L7.33355 2.66675C7.33355 2.29867 7.63152 1.99993 7.99956 1.99976C8.36775 1.99976 8.66655 2.29856 8.66655 2.66675L8.66655 11.7244L12.1949 8.19507C12.4552 7.93472 12.8779 7.93472 13.1382 8.19507Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconArrow_down', inheritAttrs: false };
</script>
