<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/se_3Rp-r8icAAAAAObAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M8.33408 13.6631C8.33478 13.6608 8.33689 13.6591 8.33932 13.659C11.8634 13.4999 14.6663 10.8779 14.6663 7.66669C14.6663 4.35298 11.6816 1.66669 7.99967 1.66669C4.31778 1.66669 1.33301 4.35298 1.33301 7.66669C1.33301 9.19765 1.97012 10.5947 3.01873 11.6548C3.19701 11.835 3.27704 12.0941 3.21034 12.3387L2.92623 13.3804C2.80192 13.8362 3.17808 14.2731 3.6473 14.2179L8.32929 13.6671C8.33154 13.6669 8.33343 13.6653 8.33408 13.6631Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M6 8H10M8 6L8 10" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconComment', inheritAttrs: false };
</script>
