<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/iPQ5R4owPGMAAAAAKpAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M13.3329 5.7915C13.3329 5.33127 12.9601 4.9585 12.4999 4.9585H3.49988C3.03964 4.9585 2.66687 5.33127 2.66687 5.7915V9.5415C2.66687 10.0017 3.03964 10.3745 3.49988 10.3745H12.4999C12.9601 10.3745 13.3329 10.0017 13.3329 9.5415V5.7915ZM14.6669 9.5415C14.6669 10.7381 13.6965 11.7085 12.4999 11.7085H3.49988C2.30326 11.7085 1.33289 10.7381 1.33289 9.5415V5.7915C1.33289 4.59489 2.30326 3.62451 3.49988 3.62451H12.4999C13.6965 3.62451 14.6669 4.59489 14.6669 5.7915V9.5415Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Icon16_9', inheritAttrs: false };
</script>
