<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/hU0pTbsGUbQAAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M1.33301 3.33331V12.6666" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M9.33301 3.33331V12.6666" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M14.6663 3.33331L10.333 7.99998L14.6663 12.6666" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M1.33301 3.33331H4.66634C6.1391 3.33331 7.33301 4.52722 7.33301 5.99998C7.33301 7.47274 6.1391 8.66665 4.66634 8.66665H1.33301" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconPk', inheritAttrs: false };
</script>
