<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/SvXXS4GepPcAAAAANIAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M12.6666 8.66694C12.6666 6.8261 11.1744 5.33313 9.33362 5.33296H4.276L5.80432 6.86225C6.06467 7.1226 6.06467 7.54429 5.80432 7.80464C5.54396 8.06482 5.12223 8.06493 4.86194 7.80464L2.19495 5.13765C1.93498 4.87732 1.93487 4.45552 2.19495 4.19526L4.86194 1.52827C5.12219 1.26819 5.544 1.2683 5.80432 1.52827C6.06467 1.78862 6.06467 2.21128 5.80432 2.47163L4.276 3.99995H9.33362C11.9108 4.00013 13.9996 6.08972 13.9996 8.66694C13.9995 11.244 11.9107 13.3328 9.33362 13.333H2.66663C2.29854 13.333 1.99981 13.035 1.99963 12.6669C1.99963 12.2988 2.29844 11.9999 2.66663 11.9999H9.33362C11.1743 11.9998 12.6665 10.5076 12.6666 8.66694Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconUndo', inheritAttrs: false };
</script>
