<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/ODGRR4UkVvMAAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_2476_65811)"> <circle cx="31.5" cy="16.5" r="10.5" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> <path d="M19.5 33L27 27" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> <path d="M39 25.5L45 30" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> <path d="M22.5 66H57.3792C59.8618 66 62.0881 64.471 62.9793 62.1539L67.4319 50.5769C68.1877 48.6119 66.7372 46.5 64.6319 46.5H44.8246C42.242 46.5 39.9491 48.1526 39.1325 50.6026L34.5 64.5" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> <path d="M21 18L9.36126 25.5905C3.96787 29.1079 3.90544 36.9862 9.24241 40.5886L15.6524 44.9154C17.1388 45.9187 18.0985 47.5343 18.2685 49.3196L19 57" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> <path d="M42 18L54.977 22.9911C58.4076 24.3106 59.8562 28.3767 58.0325 31.568L55.5 36" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> </g> <defs> <clipPath id="clip0_2476_65811"> <rect width="72" height="72" fill="currentColor" style="fill-opacity:1;"/> </clipPath> </defs> </svg>
</template>

<script lang="ts">
export default { name: 'IconLike_heart_2', inheritAttrs: false };
</script>
