<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/XTYETqn2vFMAAAAAKqAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M12.6667 4.1665C12.6667 3.70638 12.2938 3.33367 11.8337 3.3335H4.16675C3.70651 3.3335 3.33374 3.70627 3.33374 4.1665V11.8335C3.33392 12.2936 3.70662 12.6665 4.16675 12.6665H11.8337C12.2937 12.6663 12.6666 12.2935 12.6667 11.8335V4.1665ZM13.9998 11.8335C13.9996 13.0299 13.0301 13.9993 11.8337 13.9995H4.16675C2.97024 13.9995 1.99993 13.03 1.99976 11.8335V4.1665C1.99976 2.96989 2.97013 1.99951 4.16675 1.99951H11.8337C13.0302 1.99969 13.9998 2.97 13.9998 4.1665V11.8335Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Icon1_1', inheritAttrs: false };
</script>
