<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/1VECQYzK5YIAAAAAFrAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M12.8131 6.24759L5.62985 2.2968C4.29695 1.56371 2.66602 2.52803 2.66602 4.04924V11.9508C2.66602 13.472 4.29695 14.4363 5.62985 13.7032L12.8131 9.75246C14.1947 8.99261 14.1947 7.00745 12.8131 6.24759Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconPlay', inheritAttrs: false };
</script>
