<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Nj8HSbCIoHMAAAAAGJAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M3.5 5.375V4.125C3.5 3.77982 3.77982 3.5 4.125 3.5H12.875C13.2202 3.5 13.5 3.77982 13.5 4.125V5.375M8.5 3.5V13.5M6.625 13.5H10.375" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.25" stroke-linecap="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconText', inheritAttrs: false };
</script>
