<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/LqkhSY8rlE8AAAAAMSAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M10.7975 1.35698C11.9634 0.191066 13.9339 1.24515 13.611 2.86186L12.6832 7.49956H16.3209C17.8058 7.49956 18.5496 9.29531 17.4996 10.3453L9.20179 18.6431C8.03574 19.809 6.0659 18.7542 6.38929 17.1373L7.31702 12.4996H3.67835C2.19361 12.4995 1.44989 10.7048 2.49964 9.65483L10.7975 1.35698ZM3.67835 10.8335H8.33363C8.58314 10.8337 8.81996 10.9453 8.97816 11.1382C9.13625 11.3312 9.19884 11.585 9.15003 11.8296L8.02308 17.4644L16.3209 9.16655H11.6666C11.417 9.16655 11.1804 9.05486 11.0221 8.86186C10.8638 8.66879 10.8003 8.41429 10.8493 8.16948L11.9762 2.53569L3.67835 10.8335Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconBolt', inheritAttrs: false };
</script>
