<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/pY4mRLIR5O0AAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M8.66667 2H4C2.89543 2 2 2.89543 2 4V12C2 13.1046 2.89543 14 4 14H12C13.1046 14 14 13.1046 14 12V7.33333" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M2 9.33333L4.82427 6.50906C5.09887 6.23446 5.54912 6.25175 5.80185 6.5466L8.92685 10.1924C9.1555 10.4592 9.55194 10.5027 9.83302 10.2919L11.5374 9.01358C11.8029 8.81452 12.1743 8.84092 12.4088 9.07551L14 10.6667" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M12.4166 1.34237C12.5025 1.11021 12.8309 1.11021 12.9168 1.34237L13.3444 2.49793C13.3714 2.57092 13.4289 2.62847 13.5019 2.65548L14.6575 3.08308C14.8896 3.16899 14.8896 3.49736 14.6575 3.58326L13.5019 4.01086C13.4289 4.03787 13.3714 4.09542 13.3444 4.16841L12.9168 5.32397C12.8309 5.55613 12.5025 5.55613 12.4166 5.32397L11.989 4.16841C11.962 4.09542 11.9044 4.03787 11.8314 4.01086L10.6759 3.58326C10.4437 3.49736 10.4437 3.16899 10.6759 3.08308L11.8314 2.65548C11.9044 2.62847 11.962 2.57092 11.989 2.49793L12.4166 1.34237Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="0.933333" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconUserimage', inheritAttrs: false };
</script>
