<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/RotJQ4kVCVsAAAAAK3AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M16 0C24.8366 0 32 7.16344 32 16C32 24.8366 24.8366 32 16 32C7.16344 32 0 24.8366 0 16C0 7.16344 7.16344 0 16 0ZM16.4121 10.9199C16.1843 10.6926 15.8146 10.6925 15.5869 10.9199L11.5039 15.0039C11.2764 15.2316 11.2766 15.6003 11.5039 15.8281C11.7317 16.0559 12.1013 16.0559 12.3291 15.8281L15.416 12.7412V20.666C15.416 20.9882 15.6779 21.249 16 21.249C16.322 21.2488 16.583 20.9881 16.583 20.666V12.7412L19.6709 15.8281C19.8987 16.0559 20.2673 16.0559 20.4951 15.8281C20.7227 15.6003 20.7228 15.2316 20.4951 15.0039L16.4121 10.9199Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconSendV5', inheritAttrs: false };
</script>
