<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/yPW3TZ2LOe8AAAAAIPAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M11.5283 10.4717C11.7886 10.732 12.2113 10.732 12.4716 10.4717C12.732 10.2113 12.732 9.78867 12.4716 9.52832L8.82515 5.88183C8.36954 5.42627 7.63036 5.42627 7.17476 5.88183L3.52827 9.52832C3.26792 9.78867 3.26792 10.2113 3.52827 10.4717C3.78862 10.732 4.21128 10.732 4.47163 10.4717L7.99995 6.94336L11.5283 10.4717Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconChevron_top', inheritAttrs: false };
</script>
