<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/R-8dR5TxZqMAAAAAJsAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M7.05712 4.22869L7.99993 3.28588C9.30167 1.98413 11.4122 1.98413 12.714 3.28588C14.0157 4.58763 14.0157 6.69818 12.714 7.99993L11.7712 8.94274C10.4694 10.2445 8.35886 10.2445 7.05712 8.94274M8.94274 11.7712L7.99993 12.714C6.69818 14.0157 4.58763 14.0157 3.28588 12.714C1.98413 11.4122 1.98413 9.30167 3.28588 7.99993L4.22869 7.05712C5.53044 5.75537 7.64099 5.75537 8.94274 7.05712" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconLink', inheritAttrs: false };
</script>
