<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/cbsGQ7mq1nsAAAAAGaAAABgAemmSAQBr/original -->
<template>
  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" v-bind="$attrs">
<path d="M2.06592 8.6127L6.08221 3.50105C6.54932 2.90655 7.44985 2.90655 7.91696 3.50105L11.9332 8.6127C12.5347 9.37818 11.9894 10.5002 11.0159 10.5002H2.98329C2.00979 10.5002 1.46447 9.37818 2.06592 8.6127Z" fill="currentColor" style="fill-opacity:1"/>
</svg>
</template>

<script lang="ts">
export default { name: 'IconTriangle_up', inheritAttrs: false };
</script>