<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/zIUTSqiSyuUAAAAAG2AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <circle cx="7.99951" cy="12" r="3" stroke="currentColor" style="stroke-opacity:1;" stroke-width="2"/> <rect x="1.00049" y="5" width="22" height="14" rx="7" stroke="currentColor" style="stroke-opacity:1;" stroke-width="2"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconSwitch_off', inheritAttrs: false };
</script>
