<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Q1XbRZ6EcF0AAAAAMpAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M10.0007 6V2.66699C10.0007 2.2988 9.70185 2 9.33366 2C8.96547 2 8.66667 2.2988 8.66667 2.66699V6C8.66667 6.73638 9.26427 7.33398 10.0007 7.33398H13.3337C13.7018 7.33398 14.0007 7.03518 14.0007 6.66699C14.0007 6.2988 13.7018 6 13.3337 6H10.0007Z" fill="currentColor" style="fill-opacity:1;"/> <path d="M6 10.0007V13.3337C6 13.7018 6.2988 14.0007 6.66699 14.0007C7.03518 14.0007 7.33398 13.7018 7.33398 13.3337V10.0007C7.33398 9.26427 6.73638 8.66667 6 8.66667H2.66699C2.2988 8.66667 2 8.96547 2 9.33366C2 9.70185 2.2988 10.0007 2.66699 10.0007H6Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconCollapse', inheritAttrs: false };
</script>
