<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Gba5QLLpc6EAAAAAG8AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M13 6L12.4754 12.8201C12.3952 13.8621 11.5263 14.6667 10.4813 14.6667H5.51873C4.47366 14.6667 3.60477 13.8621 3.52462 12.8201L3 6M2 4H14M5.66667 2H10.3333" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconDelete', inheritAttrs: false };
</script>
