<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/-wlfRLGzwmcAAAAAFIAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <rect x="2.6665" y="1.3335" width="4" height="13.3333" rx="1" fill="currentColor" style="fill-opacity:1;"/> <rect x="9.33301" y="1.3335" width="4" height="13.3333" rx="1" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconPulse', inheritAttrs: false };
</script>
