<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/H6__TpJle8MAAAAANGAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M12.4463 13.9672C11.9943 14.6415 10.952 14.8135 10.3301 14.103L8.39844 11.8959C8.1453 11.6067 7.77987 11.4409 7.39551 11.4409H4C3.26385 11.4407 2.66712 10.843 2.66699 10.1069V6.10688C2.66711 5.58776 2.96432 5.13854 3.39746 4.91841L12.4463 13.9672Z" fill="currentColor" style="fill-opacity:1;"/> <path d="M3.52832 1.6352C3.78867 1.37485 4.21133 1.37485 4.47168 1.6352L7.59277 4.7563C7.90268 4.70979 8.1892 4.55773 8.39844 4.3188L10.3301 2.11079C11.1407 1.18453 12.6666 1.75791 12.667 2.98872V9.83052L15.4717 12.6352C15.732 12.8956 15.732 13.3182 15.4717 13.5786C15.2114 13.8389 14.7887 13.8388 14.5283 13.5786L3.52832 2.57856C3.26798 2.31822 3.268 1.89556 3.52832 1.6352Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconSound_off', inheritAttrs: false };
</script>
