<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/dM9vT6Juc24AAAAAQDAAABgAemmSAQBr/original -->
<template>
  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" v-bind="$attrs">
<path d="M11.333 10a.667.667 0 0 1 1.333 0h1.667a.667.667 0 0 1 0 1.333h-.111a5.4 5.4 0 0 1-1.183 2.32q.222.126.461.225l.42.172a.667.667 0 0 1-.506 1.233l-.42-.172a5.4 5.4 0 0 1-.995-.537c-.308.21-.64.392-.993.537l-.42.172a.667.667 0 1 1-.506-1.233l.42-.172q.24-.1.461-.226a5.4 5.4 0 0 1-1.183-2.319h-.112a.666.666 0 0 1 0-1.333zm-10 1.333V10a.667.667 0 0 1 1.333 0v1.333c0 .368.3.667.667.667h4a.666.666 0 0 1 .37 1.222l-2 1.333a.667.667 0 0 1-.74-1.11l.17-.112h-1.8a2 2 0 0 1-2-2m9.826 0c.174.55.462 1.053.841 1.48.38-.426.668-.93.842-1.48zM2.666 6V2A.667.667 0 0 1 4 2v4a.667.667 0 0 1-1.334 0m10.667 0V4.667A.667.667 0 0 0 12.666 4h-4a.667.667 0 0 1-.369-1.222l2-1.333a.667.667 0 0 1 .74 1.11l-.17.112h1.8a2 2 0 0 1 2 2V6a.667.667 0 1 1-1.334 0M.666 4.667V3.333a.667.667 0 0 1 1.334 0v1.334a.667.667 0 0 1-1.334 0m4 0V3.333a.667.667 0 0 1 1.334 0v1.334a.667.667 0 0 1-1.334 0" fill="currentColor"/>
</svg>
</template>

<script lang="ts">
export default { name: 'IconTranscription', inheritAttrs: false };
</script>
