<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/9lRaR64SJ3UAAAAALNAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M1.66732 12.6667L4.86258 9.47141C5.12293 9.21106 5.54504 9.21106 5.80539 9.4714L6.50831 10.1743C6.77669 10.4427 7.21467 10.4332 7.47115 10.1534L10.1968 7.17993C10.4533 6.90014 10.8913 6.89063 11.1597 7.15901L14.6673 10.6667M5.33398 5.33333H5.34065M3.33398 2H12.6673C13.7719 2 14.6673 2.89543 14.6673 4V12C14.6673 13.1046 13.7719 14 12.6673 14H3.33398C2.22941 14 1.33398 13.1046 1.33398 12V4C1.33398 2.89543 2.22942 2 3.33398 2Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconUserimage1', inheritAttrs: false };
</script>
