<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/d5v6QI9wGVYAAAAALmAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M3.3335 8C3.3335 7.44772 3.78121 7 4.3335 7C4.88578 7 5.3335 7.44772 5.3335 8C5.3335 8.55228 4.88578 9 4.3335 9C3.78121 9 3.3335 8.55228 3.3335 8Z" fill="currentColor" style="fill-opacity:1;"/> <path d="M7.00016 8C7.00016 7.44772 7.44788 7 8.00016 7C8.55245 7 9.00016 7.44772 9.00016 8C9.00016 8.55228 8.55245 9 8.00016 9C7.44788 9 7.00016 8.55228 7.00016 8Z" fill="currentColor" style="fill-opacity:1;"/> <path d="M10.6668 8C10.6668 7.44772 11.1145 7 11.6668 7C12.2191 7 12.6668 7.44772 12.6668 8C12.6668 8.55228 12.2191 9 11.6668 9C11.1145 9 10.6668 8.55228 10.6668 8Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconMore_he', inheritAttrs: false };
</script>
