<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/dhcyRI-W3zcAAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M48.5975 12.5495C48.1269 17.2758 42.5373 19.1887 35.9425 18.532C29.3477 17.8754 24.2695 14.6521 24.7156 10.1715C25.1617 5.69095 30.7758 3.53232 37.3706 4.18897C43.9654 4.84561 49.0681 7.82307 48.5975 12.5495Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> <path d="M48.878 23.7387C51.0894 29.3974 45.6642 34.2245 37.8397 37.2823C30.0153 40.3402 22.6129 40.1081 20.5432 34.8121C18.6291 29.9143 23.757 24.3263 31.5814 21.2685C39.4059 18.2107 46.6665 18.0801 48.878 23.7387Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> <path d="M60 51C60 60 49.2548 63 36 63C22.7452 63 12 60 12 51C12 42 22.7452 39 36 39C49.2548 39 60 42 60 51Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> <path d="M6 66H66" stroke="currentColor" style="stroke-opacity:1;" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconZen', inheritAttrs: false };
</script>
