<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/R0BnTLiCkOUAAAAAKNAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M11.0413 3.5C11.0413 3.03976 10.6685 2.66699 10.2083 2.66699H6.45825C5.99801 2.66699 5.62524 3.03976 5.62524 3.5V12.5C5.62524 12.9602 5.99801 13.333 6.45825 13.333H10.2083C10.6685 13.333 11.0413 12.9602 11.0413 12.5V3.5ZM12.3752 12.5C12.3752 13.6966 11.4049 14.667 10.2083 14.667H6.45825C5.26163 14.667 4.29126 13.6966 4.29126 12.5V3.5C4.29126 2.30338 5.26164 1.33301 6.45825 1.33301H10.2083C11.4049 1.33301 12.3752 2.30338 12.3752 3.5V12.5Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Icon9_16', inheritAttrs: false };
</script>
