<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/7M5LTbl4WFUAAAAAKTAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M10.6663 6.66675L11.9997 8.00008L10.6663 9.33341M5.33301 6.66675L3.99967 8.00008L5.33301 9.33341M7.33301 10.0001L8.66634 6.00008M3.99967 13.3334H11.9997C13.4724 13.3334 14.6663 12.1395 14.6663 10.6667V5.33341C14.6663 3.86066 13.4724 2.66675 11.9997 2.66675H3.99967C2.52692 2.66675 1.33301 3.86066 1.33301 5.33341V10.6667C1.33301 12.1395 2.52692 13.3334 3.99967 13.3334Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconCode', inheritAttrs: false };
</script>
