<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/uDijQoqKa30AAAAAPLAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M14.0706 3.88613C14.9571 3.44322 16.0003 4.08845 16.0003 5.07949V10.9213C16.0001 11.9121 14.957 12.5575 14.0706 12.1146L10.6673 10.4125V8.92129L14.6663 10.9213V5.07949L10.6673 7.07852V5.5873L14.0706 3.88613Z" fill="currentColor" style="fill-opacity:1;"/> <path d="M10 4.66638C9.99982 4.29845 9.70192 4.00054 9.33398 4.00037H2C1.63207 4.00054 1.33416 4.29845 1.33398 4.66638V11.3334C1.33398 11.7015 1.63196 12.0002 2 12.0004H9.33398C9.70202 12.0002 10 11.7015 10 11.3334V4.66638ZM11.334 11.3334C11.334 12.4378 10.4384 13.3332 9.33398 13.3334H2C0.89558 13.3332 2.57636e-07 12.4378 0 11.3334V4.66638C0.000175172 3.56207 0.895689 2.66656 2 2.66638H9.33398C10.4383 2.66656 11.3338 3.56207 11.334 4.66638V11.3334Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconCamera_angle', inheritAttrs: false };
</script>
