<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/MPAuRaqjfoIAAAAAJ2AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M5.33333 7.99992H8M9.66667 1.99992V3.99992C9.66667 4.7363 10.2636 5.33325 11 5.33325H13.3333M5.33333 10.6666H10M9.2759 1.33325H4C2.89543 1.33325 2 2.22868 2 3.33325V12.6666C2 13.7712 2.89543 14.6666 4 14.6666H12C13.1046 14.6666 14 13.7712 14 12.6666V5.60333C14 5.00978 13.7364 4.44688 13.2804 4.06689L10.5563 1.79681C10.1968 1.49728 9.74377 1.33325 9.2759 1.33325Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconPdf', inheritAttrs: false };
</script>
