<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Z7UQTZihGVsAAAAANYAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M14.0005 4C14.0005 3.26362 13.4029 2.66699 12.6665 2.66699H3.3335C2.59712 2.66699 2.00049 3.26362 2.00049 4V9.33301C2.00049 10.0694 2.59712 10.667 3.3335 10.667H12.6665C13.4029 10.667 14.0005 10.0694 14.0005 9.33301V4ZM15.3335 9.33301C15.3335 10.8058 14.1393 12 12.6665 12H8.6665V13.333H10.6665C11.0347 13.333 11.3335 13.6318 11.3335 14C11.3335 14.3682 11.0347 14.667 10.6665 14.667H5.3335C4.96531 14.667 4.6665 14.3682 4.6665 14C4.6665 13.6318 4.96531 13.333 5.3335 13.333H7.3335V12H3.3335C1.86074 12 0.666504 10.8058 0.666504 9.33301V4C0.666504 2.52724 1.86074 1.33301 3.3335 1.33301H12.6665C14.1393 1.33301 15.3335 2.52724 15.3335 4V9.33301Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconDesktop', inheritAttrs: false };
</script>
