<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/ZeNeTJAd-xQAAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="24" height="22" viewBox="0 0 24 22" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M13.1504 6.29883C14.1443 6.29906 14.878 7.10173 14.79 8.0918C14.702 9.08197 13.8251 9.88477 12.831 9.88477H11.1084L11.3701 6.29883H13.1504Z" fill="currentColor" style="fill-opacity:1;"/> <path fill-rule="evenodd" clip-rule="evenodd" d="M15.5547 1C16.7136 1.00018 17.815 1.48352 18.5693 2.32227L22.0439 6.18652C23.277 7.55798 23.3218 9.56886 22.1514 10.9893L15.0928 19.5527C13.4982 21.4872 10.4225 21.4811 8.83691 19.54L1.83788 10.9688C0.685671 9.55779 0.725905 7.57049 1.93456 6.20312L5.34374 2.34668C6.09833 1.49309 7.2099 1.00001 8.38085 1H15.5547ZM10.3623 3.9082C10.0409 3.90825 9.72135 4.03657 9.47558 4.26465C9.22972 4.49298 9.07798 4.80275 9.05468 5.12305L8.29784 15.5195C8.25003 16.1793 8.74971 16.7058 9.41308 16.6953C10.0766 16.6845 10.6541 16.1404 10.7021 15.4805L10.9355 12.2754H12.6191C14.9385 12.2752 16.985 10.4021 17.1904 8.0918C17.3958 5.78131 15.6819 3.9082 13.3623 3.9082H10.3623Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconApiColor', inheritAttrs: false };
</script>
