<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/D7s_Tb9ssdwAAAAAOXAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M4.00065 2.66669H12.0007C13.4734 2.66669 14.6673 3.86059 14.6673 5.33335V10.6667C14.6673 12.1394 13.4734 13.3334 12.0007 13.3334H4.00065C2.52789 13.3334 1.33398 12.1394 1.33398 10.6667V5.33335C1.33398 3.86059 2.52789 2.66669 4.00065 2.66669Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M9.58463 7.72267L7.51888 6.34551C7.29737 6.19783 7.00065 6.35663 7.00065 6.62286V9.37718C7.00065 9.64341 7.29737 9.80221 7.51888 9.65453L9.58463 8.27737C9.78254 8.14543 9.78254 7.85461 9.58463 7.72267Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconVideo', inheritAttrs: false };
</script>
