<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/kR5yRIn-kn0AAAAAMGAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_4452_4438)"> <path d="M14.5266 6.63842C14.6386 7.17698 14.6852 7.73825 14.6581 8.31312C14.4852 11.991 11.3636 14.8323 7.68577 14.6594C4.00794 14.4865 1.16662 11.3648 1.33952 7.68699C1.51242 4.00916 4.63406 1.16784 8.31189 1.34074C9.52485 1.39776 10.6468 1.77552 11.5997 2.38817M4.99881 7.33339L7.66548 10.0001L13.3321 4.33339" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </g> <defs> <clipPath id="clip0_4452_4438"> <rect width="16" height="16" fill="currentColor" style="fill-opacity:1;"/> </clipPath> </defs> </svg>
</template>

<script lang="ts">
export default { name: 'IconTickG', inheritAttrs: false };
</script>
