<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/6IQWRqswu-IAAAAANJAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M7 4.33333C7 3.78104 7.44772 3.33333 8 3.33333C8.55228 3.33333 9 3.78104 9 4.33333C9 4.88561 8.55228 5.33333 8 5.33333C7.44772 5.33333 7 4.88561 7 4.33333Z" fill="currentColor" style="fill-opacity:1;"/> <path d="M7 8C7 7.44771 7.44772 7 8 7C8.55228 7 9 7.44771 9 8C9 8.55228 8.55228 9 8 9C7.44772 9 7 8.55228 7 8Z" fill="currentColor" style="fill-opacity:1;"/> <path d="M7 11.6667C7 11.1144 7.44772 10.6667 8 10.6667C8.55228 10.6667 9 11.1144 9 11.6667C9 12.2189 8.55228 12.6667 8 12.6667C7.44772 12.6667 7 12.2189 7 11.6667Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconMore_v', inheritAttrs: false };
</script>
