<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/PC4MR4Oj2_IAAAAAMuAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M12.5288 8.66694C13.4194 8.66725 13.8657 9.74409 13.2358 10.374L11.1382 12.4716C10.8778 12.732 10.4552 12.732 10.1948 12.4716C9.93447 12.2113 9.93447 11.7886 10.1948 11.5283L11.7231 9.99995H2.6665C2.29831 9.99995 1.99951 9.70115 1.99951 9.33296C1.99969 8.96492 2.29842 8.66694 2.6665 8.66694H12.5288ZM4.86182 3.52827C5.12207 3.26819 5.54388 3.2683 5.8042 3.52827C6.06455 3.78862 6.06455 4.21128 5.8042 4.47163L4.27588 5.99995H13.3335C13.7015 6.00013 13.9995 6.29886 13.9995 6.66694C13.9993 7.03487 13.7014 7.33278 13.3335 7.33296H3.47119C2.58032 7.33292 2.13421 6.25588 2.76416 5.62593L4.86182 3.52827Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconArrow_swap', inheritAttrs: false };
</script>
