<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/dfX3QopfJiMAAAAAMZAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M14.0004 15V14H2.66638C1.56196 13.9998 0.666382 13.1045 0.666382 12V4C0.666382 2.89554 1.56196 2.00018 2.66638 2H14.0004V1C14.0004 0.631919 14.2983 0.333184 14.6664 0.333008C15.0346 0.333008 15.3334 0.63181 15.3334 1V15C15.3334 15.3682 15.0346 15.667 14.6664 15.667C14.2983 15.6668 14.0004 15.3681 14.0004 15ZM2.00037 9.33301H6.00037V6.66699H2.00037V9.33301ZM2.00037 12C2.00037 12.3681 2.29834 12.6668 2.66638 12.667H6.00037V10.667H2.00037V12ZM2.00037 5.33301H6.00037V3.33301H2.66638C2.29834 3.33318 2.00037 3.63192 2.00037 4V5.33301ZM7.33337 12.667H14.0004V3.33301H7.33337V12.667Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'IconFirstframe', inheritAttrs: false };
</script>
