<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/gyH_TI8uKRkAAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_1829_28858)"> <path d="M14.0004 8.00024C14.0004 4.68664 11.3139 2.00042 8.00037 2.00024C4.68666 2.00024 2.00037 4.68654 2.00037 8.00024C2.00054 11.3138 4.68677 14.0002 8.00037 14.0002C11.3138 14.0001 14.0002 11.3137 14.0004 8.00024ZM7.33337 5.33325C7.33337 4.96506 7.63218 4.66626 8.00037 4.66626C8.36841 4.66644 8.66638 4.96517 8.66638 5.33325V7.72388L10.4711 9.52856C10.7314 9.78891 10.7314 10.2106 10.4711 10.4709C10.2107 10.7313 9.78904 10.7313 9.52869 10.4709L7.52869 8.47095C7.40384 8.34602 7.33346 8.17686 7.33337 8.00024V5.33325ZM15.3334 8.00024C15.3332 12.0501 12.0502 15.3331 8.00037 15.3333C3.95039 15.3333 0.666558 12.0502 0.666382 8.00024C0.666382 3.95016 3.95028 0.66626 8.00037 0.66626C12.0503 0.666436 15.3334 3.95026 15.3334 8.00024Z" fill="currentColor" style="fill-opacity:1;"/> </g> <defs> <clipPath id="clip0_1829_28858"> <rect width="16" height="16" fill="currentColor" style="fill-opacity:1;"/> </clipPath> </defs> </svg>
</template>

<script lang="ts">
export default { name: 'IconClock', inheritAttrs: false };
</script>
