<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/dM_mR5SNsg8AAAAANXAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="17" height="16" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M5.66406 5.33325V5.33992" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round"/> <path d="M1.9974 12.6667L5.19266 9.47141C5.45301 9.21106 5.87512 9.21106 6.13547 9.4714L6.83838 10.1743C7.10677 10.4427 7.54475 10.4332 7.80122 10.1534L10.5269 7.17993C10.7834 6.90014 11.2214 6.89063 11.4897 7.15901L14.9974 10.6667M3.66406 14H12.9974C14.102 14 14.9974 13.1046 14.9974 12V4C14.9974 2.89543 14.102 2 12.9974 2H3.66406C2.55949 2 1.66406 2.89543 1.66406 4V12C1.66406 13.1046 2.55949 14 3.66406 14Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'Image', inheritAttrs: false };
</script>
