<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/jWd-QpnnNrwAAAAAN3AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="14" height="15" viewBox="0 0 14 15" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M11.6673 6.33317C11.6673 10.4165 7.00065 13.3332 7.00065 13.3332C7.00065 13.3332 2.33398 10.4165 2.33398 6.33317C2.33398 3.75584 4.42332 1.6665 7.00065 1.6665C9.57798 1.6665 11.6673 3.75584 11.6673 6.33317Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round"/> <path d="M8.16732 6.33317C8.16732 5.68884 7.64498 5.1665 7.00065 5.1665C6.35632 5.1665 5.83398 5.68884 5.83398 6.33317C5.83398 6.9775 6.35632 7.49984 7.00065 7.49984C7.64498 7.49984 8.16732 6.9775 8.16732 6.33317Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'MapPin', inheritAttrs: false };
</script>
