<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/xn9UQ6ZTtbYAAAAAQBAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="14" height="15" viewBox="0 0 14 15" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M1.16602 2.8335V5.16683H3.49935" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round"/> <path d="M1.86523 4.73114C2.36104 3.80965 3.11085 3.01014 4.08363 2.44851C6.87367 0.837677 10.4413 1.79362 12.0521 4.58366C12.4776 5.32066 12.724 6.11191 12.8048 6.90703" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round"/> <path d="M1.17383 7.83194C1.22343 8.71438 1.47506 9.59886 1.94715 10.4166C3.55798 13.2066 7.12559 14.1625 9.91563 12.5517C11.9656 11.3681 13.0254 9.12821 12.8045 6.9165" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.16667" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="0.58 1.75"/> </svg>
</template>

<script lang="ts">
export default { name: 'Refresh', inheritAttrs: false };
</script>
