<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/owbBTZr5Lf4AAAAAHIAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M4.40973 5C3.22213 6.32689 2.5 8.07911 2.5 10C2.5 14.1421 5.85786 17.5 10 17.5C14.1421 17.5 17.5 14.1421 17.5 10C17.5 8.07911 16.7779 6.32689 15.5903 5M10 2.5V9.16667" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'Shutdown', inheritAttrs: false };
</script>
