<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/AnG3RIq-HCwAAAAAK1AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg"> <g opacity="0.85"> <path d="M6.66797 5.83341L4.66797 3.83341M4.66797 3.83341L2.66797 5.83341M4.66797 3.83341L4.66797 13.1667" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> <path d="M9.33594 11.1667L11.3359 13.1667M11.3359 13.1667L13.3359 11.1667M11.3359 13.1667L11.3359 3.83337" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/> </g> </svg>
</template>

<script lang="ts">
export default { name: 'Sort', inheritAttrs: false };
</script>
