<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/IFStSajTAzEAAAAAETAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M2.66797 8.5L6.0013 11.8333L13.3346 4.5" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'Tick', inheritAttrs: false };
</script>
