<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/lj8HS4J_4_MAAAAAGgAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M4.6115 7.38743L7.28647 10.5974C7.65976 11.0453 8.34774 11.0453 8.72103 10.5974L11.396 7.38743C11.9028 6.7793 11.4703 5.85602 10.6787 5.85602L5.32878 5.85602C4.53717 5.85602 4.10472 6.7793 4.6115 7.38743Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'TriangleDown', inheritAttrs: false };
</script>
