<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/m3GKQKcLe9AAAAAADiAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="8" height="10" viewBox="0 0 8 10" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M8 5L0 10V0L8 5Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Triangle', inheritAttrs: false };
</script>
