<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/O6SYQaRnxKoAAAAAGbAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M7.38742 11.3885L10.5974 8.71353C11.0453 8.34024 11.0453 7.65226 10.5974 7.27897L7.38742 4.604C6.77928 4.09723 5.856 4.52967 5.856 5.32128L5.856 10.6712C5.856 11.4628 6.77928 11.8953 7.38742 11.3885Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'TriangleRight', inheritAttrs: false };
</script>
