<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/axA9TrKEpRUAAAAAGRAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M17.2719 3.58661H20.0831L13.9414 10.6062L21.1667 20.1582H15.5094L11.0784 14.365L6.0083 20.1582H3.19537L9.76454 12.65L2.83334 3.58661H8.63427L12.6395 8.88189L17.2719 3.58661ZM16.2853 18.4756H17.843L7.78784 5.18089H6.11623L16.2853 18.4756Z" fill="currentColor" style="fill-opacity:1;"/> </svg>
</template>

<script lang="ts">
export default { name: 'Twitter', inheritAttrs: false };
</script>
