<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/qda-Tbz8Ws4AAAAAN0AAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M17.368 13.0424C16.8591 14.246 16.063 15.3066 15.0495 16.1314C14.036 16.9563 12.8359 17.5203 11.5541 17.7742C10.2722 18.028 8.94771 17.964 7.69632 17.5878C6.44492 17.2115 5.30475 16.5344 4.37549 15.6157C3.44622 14.697 2.75616 13.5646 2.36562 12.3176C1.97509 11.0706 1.89597 9.7469 2.1352 8.46225C2.37442 7.17759 2.9247 5.97109 3.73792 4.94824C4.55114 3.92538 5.60255 3.11731 6.80022 2.59466M18 9.93049C18 8.87994 17.7931 7.83967 17.391 6.86909C16.989 5.89851 16.3998 5.01661 15.6569 4.27376C14.9141 3.53091 14.0322 2.94164 13.0616 2.53961C12.091 2.13759 11.0507 1.93066 10.0002 1.93066V9.93049H18Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.66" stroke-linecap="round" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'Usage', inheritAttrs: false };
</script>
