<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/Cf0FRIlee-YAAAAAOeAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_574_55343)"> <path d="M8.00098 0.666504C12.0511 0.666504 15.334 3.9504 15.334 8.00049C15.3337 12.0504 12.0509 15.3335 8.00098 15.3335C3.95105 15.3335 0.668233 12.0504 0.667969 8.00049C0.667969 3.9504 3.95089 0.666504 8.00098 0.666504ZM11.8057 5.52881C11.5453 5.26849 11.1236 5.26854 10.8633 5.52881L7.33398 9.05713L5.80566 7.52881C5.54534 7.26849 5.12364 7.26854 4.86328 7.52881C4.60293 7.78916 4.60293 8.21084 4.86328 8.47119L6.86328 10.4712C7.12364 10.7315 7.54534 10.7315 7.80566 10.4712L11.8057 6.47119C12.0659 6.21086 12.0659 5.78914 11.8057 5.52881Z" fill="currentColor" style="fill-opacity:1;"/> </g> <defs> <clipPath id="clip0_574_55343"> <rect width="16" height="16" fill="currentColor" style="fill-opacity:1;"/> </clipPath> </defs> </svg>
</template>

<script lang="ts">
export default { name: 'Verify', inheritAttrs: false };
</script>
