<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/CI0cTqPThO4AAAAAMoAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="17" height="16" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M1.66406 4C1.66406 2.89543 2.55949 2 3.66406 2H12.9974C14.102 2 14.9974 2.89543 14.9974 4V12C14.9974 13.1046 14.102 14 12.9974 14H3.66406C2.55949 14 1.66406 13.1046 1.66406 12V4Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linejoin="round"/> <path d="M7.33073 9.37716V6.62284C7.33073 6.35661 7.62744 6.19781 7.84896 6.34549L9.9147 7.72265C10.1126 7.85459 10.1126 8.14541 9.9147 8.27735L7.84896 9.65451C7.62744 9.80219 7.33073 9.64339 7.33073 9.37716Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linejoin="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'Video', inheritAttrs: false };
</script>
