<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/ocZeTorONT4AAAAAIGAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="17" height="16" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M8.33073 6V10M6.33073 7V9M10.3307 7V9M12.3307 8V8.00667M4.33073 8V8.00667M3.66406 14H12.9974C14.102 14 14.9974 13.1046 14.9974 12V4C14.9974 2.89543 14.102 2 12.9974 2H3.66406C2.55949 2 1.66406 2.89543 1.66406 4V12C1.66406 13.1046 2.55949 14 3.66406 14Z" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.33333" stroke-linecap="round"/> </svg>
</template>

<script lang="ts">
export default { name: 'Voice', inheritAttrs: false };
</script>
