<!-- Auto generated by scripts/load-icons.ts — do not edit -->
<!-- https://mass-office.alipay.com/design_kitchen/afts/img/SH3pR6guqfwAAAAAMCAAABgAemmSAQBr/original -->
<template>
  <svg v-bind="$attrs" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M5.83333 4.93073L10.1963 2.36013C11.2721 1.68775 12.6809 1.92775 13.4735 2.91839L15 4.93073M15 4.93073H5C3.61929 4.93073 2.5 6.05001 2.5 7.43072V14.9307C2.5 16.3114 3.61929 17.4307 5 17.4307H15C16.3807 17.4307 17.5 16.3114 17.5 14.9307V13.2641M15 4.93073C16.3807 4.93073 17.5 6.05001 17.5 7.43072V9.09739M17.5 9.09739H14.5833C13.4327 9.09739 12.5 10.0301 12.5 11.1807C12.5 12.3313 13.4327 13.2641 14.5833 13.2641H17.5M17.5 9.09739C17.9602 9.09739 18.3333 9.47049 18.3333 9.93072V12.4307C18.3333 12.891 17.9602 13.2641 17.5 13.2641" stroke="currentColor" style="stroke-opacity:1;" stroke-width="1.66"/> </svg>
</template>

<script lang="ts">
export default { name: 'Wallet', inheritAttrs: false };
</script>
