name: Feature Request
description: Suggest a new feature or improvement for the documentation
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
      placeholder: |
        I'm trying to find information about...
        Currently, the docs don't explain...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this feature to work?
      placeholder: |
        Add a new page about...
        Include code examples for...
        Add a search filter for...
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Which area does this feature relate to?
      description: Select all that apply
      multiple: true
      options:
        - Content (new documentation page)
        - Translation improvements
        - Code examples
        - Navigation/sidebar
        - Search functionality
        - UI/UX improvements
        - Images/diagrams
        - Video tutorials
        - API reference
        - Configuration examples
        - Troubleshooting guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which language should this feature be added to?
      options:
        - English
        - Chinese (简体中文)
        - Both
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples from other documentation sites
      description: Are there similar features in other docs that inspired this?
      placeholder: |
        VitePress docs have a feature where...
        Next.js docs show...
        Vercel docs include...

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Critical - Blocking my understanding
        - High - Would significantly improve the docs
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, mockups, or examples
      placeholder: |
        Here's a draft of the content...
        This would help users who...
        Related to issue #123

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR to implement this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with ZenMux documentation goals
          required: true
